name: Deploy to PebbleHost

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build site
        run: npm run build

      - name: Include .htaccess and .cpanel.yml in dist
        run: |
          echo "📄 Copying .htaccess and .cpanel.yml to dist/"
          cp .htaccess dist/.htaccess
          cp .cpanel.yml dist/.cpanel.yml
          echo "📁 Contents of dist/ after copy:"
          ls -al dist/

      - name: Deploy to production branch (dist-only, keep history)
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "🚀 Deploying dist/ to 'production' branch with history..."

          # Sanity check
          if [ ! -d "dist" ]; then
            echo "❌ Build output missing. Aborting."
            exit 1
          fi

          # Clone the production branch into a temp dir
          DEPLOY_DIR=$(mktemp -d)
          echo "📦 Cloning production branch into: $DEPLOY_DIR"
          git clone --branch production https://x-access-token:${GH_TOKEN}@github.com/revathiest/PFCWebsite.git "$DEPLOY_DIR"

          # Wipe everything except .git and its contents
          echo "🧹 Cleaning out old files..."
          find "$DEPLOY_DIR" -mindepth 1 -not -path "$DEPLOY_DIR/.git*" -exec rm -rf {} +

          # Copy new build into deploy dir
          echo "📥 Copying new files..."
          cp -r dist/. "$DEPLOY_DIR"

          # Commit and push
          cd "$DEPLOY_DIR"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🚀 Deploy static site" || echo "ℹ️ Nothing to commit"
          git push origin production

          echo "✅ Deployment complete!"