name: Deploy to PebbleHost

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build site
        run: npm run build

      - name: Deploy dist to production branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin production
          git worktree add temp-deploy production
          cp -r dist/* temp-deploy/
          cd temp-deploy
          git add --all
          git commit -m "Deploy from GitHub Actions"
          git push origin production --force
