name: Deploy to PebbleHost

on:
  push:
    branches:
      - main  # or whichever branch you work from
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy dist to production branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin production
          git switch --orphan temp-deploy
          git --work-tree dist add --all
          git --work-tree dist commit -m "Deploy from GitHub Actions"
          git push origin temp-deploy:production --force

