name: Deploy to PebbleHost

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build site
        run: npm run build

      - name: Deploy to production branch (dist-only)
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "🚀 Deploying dist/ to orphan branch 'production'..."

          # Sanity check
          if [ ! -d "dist" ]; then
            echo "❌ Build output missing. Aborting."
            exit 1
          fi

          # Make a clean deploy directory
          DEPLOY_DIR=$(mktemp -d)
          cp -r dist/* "$DEPLOY_DIR"
          cd "$DEPLOY_DIR"

          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/revathiest/PFCWebsite.git
          git checkout --orphan production
          git add .
          git commit -m "🚀 Deploy static site"
          git push --force origin HEAD:production
